using UnityEngine;
using System.Collections;

public class Gui : MonoBehaviour 
{
    public GUITexture HP_bar; //ネR兵瓜
    public GUIText HP_text;   //ネR计趣濡r
    public Creature imformation; //ネ戈Tscript    

	// Use this for initialization
	void Start () {
	
	}	
	// Update is called once per frame
	void Update () 
    {                
        HP_bar.pixelInset = new Rect() //Rectx
        {
            x = HP_bar.pixelInset.x, //x旄m单蟓歃旄m
            y = HP_bar.pixelInset.y, //y旄m单蟓歃旄m
            width = 196 * imformation.HP / imformation.Max_HP, //e椎ォ 瓜e196 * 逞l宥qX% (ヘe宥q/程j宥q) 
            height = HP_bar.pixelInset.height //蔼单蟓欷jp
        };
        HP_text.text = string.Format("{0:0}/{1:0}", imformation.HP, imformation.Max_HP);//{0:d}/{1:d} 0聿膜@影鸭 d砭慵 
	}
    void OnGUI()
    {
        if (GUI.Button(new Rect(10, 80, 150, 100), "ΙHP"))
        {
            imformation.HP-=10; //Ι宕刚
        }
    }
}
